name: postman test
on: [push]
jobs:
  run-postmain-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16,18]


    steps:
      - name: Checkout Repository
        uses: actions/checkout/@v4

      - name: install node
        uses: actions/setup-node/@v4  
        with:
          node-version: ${{matrix.version}}

      - name: install newman
        run: npm install -g newman

      - name: run neweman
        run: newman run postman_tests/Books.postman_collection.json -e postman_tests/test.postman_environment.json

      
      