name: postman test
on: [push]
jobs:
  run-postmain-test:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout/@v4

      - name: install node
        uses: actions/setup-node/@v4  
        with:
          node-version: 18

      - name: install nodeman
        run: npm install -g nodeman

      - name: run nodeman
        run: nodeman run postman_tests\Books.postman_collection.json -e postman_tests\test.postman_environment.json

      
      